# Mac OS X Python build
language:
- objective-c

python:
- "2.7"

install:
#- brew install cmake
- brew install python
- ls /usr/local/bin
- which python
- brew link --overwrite python
- which python
- pip install --upgrade pip
- pip freeze
- pip install conda
- conda init
- conda install --yes matplotlib
- conda install --yes scipy numpy=1.8
- conda install --yes 'numpy<1.9.0'
- conda install --yes wxpython
- pip install cython
- pip install wheel
- pip install sympy
- pip install git+git://github.com/pyinstaller/pyinstaller.git@779d07b236a943a4bf9d2b1a0ae3e0ebcc914798
- pip freeze
- which python
- python setup.py develop

script:
- python setup.py bdist_wheel

