# Mac OS X Python build
language:
- objective-c

python:
- "2.7"

install:
# install python via brew
- brew install python
# make brews python the system default
- brew link --overwrite python
- which python
- python --version
# pip init
- pip install --upgrade pip
# use anaconda
- pip install conda
- conda init
- conda install --yes matplotlib
- conda install --yes scipy numpy=1.8
- conda install --yes 'numpy<1.9.0'
- conda install --yes wxpython
# final pip installs
- pip install cython
- pip install wheel
- pip install sympy
- pip install git+git://github.com/pyinstaller/pyinstaller.git@779d07b236a943a4bf9d2b1a0ae3e0ebcc914798
# show packages
- pip freeze
# build extensions
- python setup.py develop

script:
# Create wheel pacakge
- python setup.py bdist_wheel
# Create binary
- ./freeze_pyinstaller/macOSx_bundle_script.sh
- ls -l
- ls -l dist/

after_script:
# upload?
- ls -l
- ls -l dist/
