notifications:
  email: false
env:
  global:
    - GH_REF: github.com/FCS-analysis/PyCorrFit.git
sudo: required
cache:
  directories:
  # data files for testing
  - tests/data
matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      language: python
      python: 3.6
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: linux
      dist: trusty
      language: python
      python: 3.6
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    - os: osx
      language: generic
install:
- source ./.travis/${TRAVIS_OS_NAME}_install.sh
- python -m pip install -e .
- python -m pip freeze
script:
- source ./.travis/test.sh
# Distribution files are copied to the "dist" directory
- source ./.travis/${TRAVIS_OS_NAME}_dist.sh
deploy:
  provider: pypi
  user: "ci_qpi"
  password:
    secure: "K11y6w6bw8pu1iCTXCSnZJ7H++aU4dud/qOl962SvI+LV+qn4JNQQ+MtD90p6RFejjQyZZF5xCuupVwwIyHDNJjauBmzrn7M4gPyKpoEyTPhh1ZVBlY5AK8CNUzMjaV6xNZwm4abSp+eJ+RE1JMdJNqH2H5urlpYfwqhOMCBa4U="
  on:
    tags: true
  distributions: ""
  skip_cleanup: true

