notifications:
  email: false

env:
  global:
    GH_REF: github.com/FCS-analysis/PyCorrFit.git

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    - os: osx

install:
- source ./.travis/${TRAVIS_OS_NAME}_install.sh
- python setup.py develop
- pip freeze

script:
- source ./.travis/${TRAVIS_OS_NAME}_test.sh
# Distribution files are copied to the "dist" directory
- source ./.travis/${TRAVIS_OS_NAME}_dist.sh

# This section was created with
# sudo apt-get install ruby-dev
# sudo gem install travis
# travis setup releases
deploy:
  provider: releases
  api_key:
    secure: eWTrAAu/Vxyi6RJo/mcylI19Ux1dKqgA++7J8OS3vbTEMTSeJa0gfATQGzBNpWxNu+uKolIh1p+GZE5ERk+M9A1dNg3XMjrsHBED66lDt/TYUiShm/Ro2zRY5q/CyZ0AkRtvgkYWCwktwe7WKrLaVYSD7xbopQViauP43JPHzgQ=
  skip_cleanup: true
  file_glob: true
  file: dist/*
  on:
    repo: FCS-analysis/PyCorrFit
    tags: true

