notifications:
  email: false

env:
  global:
    GH_REF: github.com/FCS-analysis/PyCorrFit.git
    # GITHUB_API_TOKEN for tests
    secure: "WhXXDXgr5gHtzEoFmlxmHJIUSBUBuYBXTI96Ir7BX9gG298E/qlKWeD9Bl+Mabhlvd/VqOAz73hRms0IjyZsoYSDRDxsbGbeI27+GzqBXtcFrexT09PIu24cay2oJ2bhUoDl/6u12+4ChCvAa1+OCJZb2U54B3RIkDME4WSOlUE="

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    - os: osx
   allow_failures:
    - os: osx

install:
- source ./.travis/${TRAVIS_OS_NAME}_install.sh
- python setup.py develop
- pip freeze

script:
- source ./.travis/test.sh
# Distribution files are copied to the "dist" directory
- source ./.travis/${TRAVIS_OS_NAME}_dist.sh

# This section was created with
# sudo apt-get install ruby-dev
# sudo gem install travis
# travis setup releases
deploy:
  provider: releases
  api_key:
    secure: aTI/VjS00ykcu7usyGlBsXBEK/RIaGdSFtYEIVNVdYk0vK9yzA/mfifmiz2klzJOrBxmnhIVUBnQAhLmW2QBPphVLVMWkPl/CBz/yCGJLDxiMm4DZhkoivKfLZX/2SQ6Aua3wciEHo/sbFhywKFbVARUXGgpmDXVYtJ706OR/ZA=
  skip_cleanup: true
  file_glob: true
  file: dist/*
  on:
    repo: FCS-analysis/PyCorrFit
    tags: true

