# Mac OS X Python build
# If Travis does not build, try this:
# Change something in the repo
#  git commit -a -m "new version"
#  git tag ...
#  git push origin master && git push --tags
# 
# Do not send email notifications
notifications:
  email: false

env:
  global:
    # GitHub API access via GH_READ_API_TOKEN
    secure: "MJ+GllVS6JeRPKrxCAhRrl/YLrAL+PMrWKa/C81mVGrWak1DO121DsbQc/G+DUASS37G/ErNqkNFN6gTxssKlewIk1SJ5oYVBkrZSagTVNDcb1XNzyPFiDX32uxz68sGJ8AMEa0GQbXnM0DF6ASgZYi7DnGPSyiFfgxERFtMOh8="

matrix:
  include:
    # only run tests
    - os: linux
      language: python
      sudo: required
    # deploy linux with docker
    - os: linux
      install: true
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    # deploy linux  with docker
    - os: linux
      install: true
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    # Mac
    - os: osx
      language: python

install:
- source ./ci_${TRAVIS_OS_NAME}/install.sh
- pip freeze
- python setup.py develop
- pip install coverage coveralls
# testing and coverage
- coverage run --source=pycorrfit ./setup.py test
- coverage report -m
- coveralls

script:
# distribution packages
- source ./ci_${TRAVIS_OS_NAME}/dist.sh

# This section was created with
# sudo apt-get install ruby1.9.1-dev
# sudo gem install travis
# travis setup releases
deploy:
  provider: releases
  api_key:
    secure: gQu6BKSo5sucrieOvyLz/kn5Ai+vrnXK6Kdm+WMqzXE6keE0LzujXOHWQX2G2EBl1NCjzvt3HrEvJqwGEjLbduJBBPBHaOy71AfKuHaxRQPlFWMLn2iAVVval3q7xU4kEfjAdS50WmARqh6sT7gMj+pHpg1e3pz1SxybOeC40+k=
  # Do not remove dist files
  skip_cleanup: true
  # Allow wildcards
  file_glob: true
  file: 
    - dist/*
  on:
    tags: true
    repo: FCS-analysis/PyCorrFit
