notifications:
  email: false

env:
  global:
    GH_REF: github.com/FCS-analysis/PyCorrFit.git
    # GITHUB_API_TOKEN for tests
    secure: "Cm5bTzC3lRqHOl4bU4+35SeW9dIu0vOBJqi3BVQhBSd5D    +4Vw7afZ9EuGFTJyT1EH30gK6Nas+K+v5wHYPc2ZB19Ublan+Z+Z+7bQByi+zQnY6iJI+4HHYZVdGmZA+hhj1FVYJyHwsHWY2i1UgEIY2VAnMp47Q7dlFSaHET/tng="

sudo: required

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    - os: osx

install:
- source ./.travis/${TRAVIS_OS_NAME}_install.sh
- python setup.py develop
- pip freeze

script:
- source ./.travis/test.sh
# Distribution files are copied to the "dist" directory
- source ./.travis/${TRAVIS_OS_NAME}_dist.sh

# This section was created with
# sudo apt-get install ruby-dev
# sudo gem install travis
# travis setup releases
deploy:
  provider: releases
  api_key:
    secure: "E982QtcvWPURFmhCuuojgk+k1olbjnByB1/ZEvf2EC6vTZI22KZ2r4szzYm3ZRjZzGNZ2P9/zkeDPcLxx4YmjwOvr/4gIesSUXK7OoK+Thgay4b7gJQgGhok9g2oXf8HicfPAdkTitg5QPt6NXIyk9N8tir10gVHlM/makEwmy4="
  skip_cleanup: true
  file_glob: true
  file: dist/*
  on:
    repo: FCS-analysis/PyCorrFit
    tags: true

