notifications:
  email: false
sudo: required
cache:
  directories:
  # data files for testing
  - tests/data
matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      language: python
      python: 3.6
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: linux
      dist: trusty
      language: python
      python: 3.6
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    - os: osx
      language: generic
install:
- source ./.travis/${TRAVIS_OS_NAME}_install.sh
- python -m pip install -e .
- python -m pip freeze
script:
- source ./.travis/test.sh
# Distribution files are copied to the "dist" directory
- source ./.travis/${TRAVIS_OS_NAME}_dist.sh
deploy:
  provider: pypi
  user: "ci_fcs"
  password:
    secure: "dKtIjzQ84Kcg1XhFzwkTwg7XdGkAH1ErHjOaKIL+0DuyGSAJ3qvhhlWReTCp0hKEhVt8Xk4HS5K2VHDTCcaRX5SKRvTmML+foaZSCqEbjjUBIhyn0EW3keSdL1jzP8vzD+0IQATBUvfbCwcSwQJ54ePtBSpZXbAeSOXcXloyBBU="
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
