# Mac OS X Python build
language:
- objective-c
python:
- "2.7"
install:
# install python via brew
- brew install python
# make brews python the system default
- brew link --overwrite python
- which python
- python --version
# pip init
- pip install --upgrade pip
# use anaconda
- pip install conda
- conda init
- conda install --yes matplotlib
- conda install --yes scipy numpy=1.8
- conda install --yes 'numpy<1.9.0'
- conda install --yes wxpython
# final pip installs
- pip install cython
- pip install wheel
- pip install sympy
- pip install git+git://github.com/pyinstaller/pyinstaller.git@779d07b236a943a4bf9d2b1a0ae3e0ebcc914798
# show packages
- pip freeze
# build extensions
- python setup.py develop
script:
# Create wheel pacakge
- python setup.py bdist_wheel
# Create binary
- ./freeze_pyinstaller/macOSx_bundle_script.sh
# This section was created with
# sudo apt-get install ruby1.9.1-dev
# sudo gem install travis
# travis setup releases
deploy:
  provider: releases
  api_key:
    secure: gQu6BKSo5sucrieOvyLz/kn5Ai+vrnXK6Kdm+WMqzXE6keE0LzujXOHWQX2G2EBl1NCjzvt3HrEvJqwGEjLbduJBBPBHaOy71AfKuHaxRQPlFWMLn2iAVVval3q7xU4kEfjAdS50WmARqh6sT7gMj+pHpg1e3pz1SxybOeC40+k=
  file: 
    - ./dist/PyCorrFit*.zip
    - ./dist/PyCorrFit*.whl
  skip_cleanup: true
  on:
    repo: paulmueller/PyCorrFit
    tags: true
