environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\freeze_appveyor\\run_with_compiler.cmd"

  matrix:
    - PYTHON: "C:\\Python27-conda32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      PYWIN_BIN: "pywin32-219.win32-py2.7.exe"

    - PYTHON: "C:\\Python27-conda64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      PYWIN_BIN: "pywin32-219.win-amd64-py2.7.exe"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  # Install InnoSetup and add to path
  # Copied from
  # https://github.com/Phonations/Joker/blob/master/appveyor.yml
  - choco install -y InnoSetup
  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - "powershell freeze_appveyor\\install.ps1"
  
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"


  # Check that we have the expected version and architecture for Python
  - "python --version"
  
  # Install the build dependencies of the project. 
  - "pip install cython"
  - "pip install wheel"
  
  # Install package-specific libraries  
  - "pip install matplotlib"
  - "pip install sympy"
  
  # Install pyinstaller
  - "ECHO Downloading https://downloads.sourceforge.net/project/pywin32/pywin32/Build 219/%PYWIN_BIN%"
  - ps: (new-object net.webclient).DownloadFile('https://downloads.sourceforge.net/project/pywin32/pywin32/Build 219/%PYWIN_BIN%', 'C:/%PYWIN_BIN%')
  - "%PYTHON%/Scripts/easy_install.exe C:/%PYWIN_BIN%"
  - "pip install git+git://github.com/pyinstaller/pyinstaller.git@779d07b236a943a4bf9d2b1a0ae3e0ebcc914798"

  # Run develop (installs yet missing packages and runs cython)
  - "%WITH_COMPILER% %PYTHON%/python setup.py develop"

  # Show the installed packages
  - "pip freeze"

shallow_clone: true

build: off

test_script:
  - "%WITH_COMPILER% %PYTHON%/python setup.py test"

after_test:
  # If tests are successful, create a whl package for the project.
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wheel"
  - ps: "ls dist"
  # Run pyinstaller
  # This will create the "win7_innosetup.iss" file
  - "freeze_pyinstaller\\win7_32bit_bundle_script.bat"
  # Create InnoSetup installers
  # Set InnoSetup path here, because Cython complained about it.
  - set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"
  - iscc win7_innosetup.iss

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*
  # InnoSetup files
  - path: Output\*
