name: Release to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build sdist
        run: pipx run build --sdist

      - name: publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PWD }}
        run: |
          pipx install twine
          twine upload --skip-existing dist/*

  build_wheels:
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build sdist
        run: pipx run build --wheel

      - name: publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PWD }}
        run: |
          pipx install twine
          twine upload --skip-existing dist/*
